"""Compare pipeline outputs against local PCRedux decision tables when identifiers reconcile cleanly."""

from __future__ import annotations

import argparse
import csv
import io
import json
import tarfile
from pathlib import Path


def _decision_rows(tarball: Path, member_name: str) -> list[dict]:
    with tarfile.open(tarball, "r:gz") as archive:
        payload = archive.extractfile(member_name)
        if payload is None:
            raise ValueError(f"Could not read {member_name} from {tarball}")
        return list(csv.DictReader(io.StringIO(payload.read().decode("utf-8", errors="replace"))))


def _well_calls(path: Path) -> list[dict]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def _decision_to_expected(row: dict) -> str:
    votes = [row["test.result.1"], row["test.result.2"], row["test.result.3"]]
    if all(vote == "y" for vote in votes):
        return "amplified"
    if all(vote == "n" for vote in votes):
        return "not_amplified"
    return "ambiguous"


def _stepone_key(call: dict) -> str:
    sample_type = "ntc" if call["sample_id"].startswith("NTC") else "unkn"
    return f"{call['well_id']}~{call['sample_id']}~{sample_type}~{call['target_id']}~{call['run_id']}"


def compare_stepone(well_calls_path: Path, tarball: Path) -> dict:
    calls = _well_calls(well_calls_path)
    observed = {_stepone_key(call): call for call in calls}
    decisions = _decision_rows(tarball, "PCRedux/inst/decision_res_stepone_std.csv")

    matched = 0
    label_matches = 0
    mismatches = []
    for row in decisions:
        key = row["stepone_std"]
        call = observed.get(key)
        if call is None:
            continue
        matched += 1
        expected = _decision_to_expected(row)
        actual = call["call_label"]
        if expected == actual:
            label_matches += 1
        else:
            mismatches.append(
                {
                    "key": key,
                    "expected": expected,
                    "actual": actual,
                    "qc_status": call["qc_status"],
                    "qc_flags": call["qc_flags"],
                }
            )

    return {
        "fixture": "stepone_std",
        "decision_rows": len(decisions),
        "matched_rows": matched,
        "label_matches": label_matches,
        "label_match_rate": round(label_matches / matched, 6) if matched else 0.0,
        "mismatches": mismatches[:25],
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Compare a well_calls.csv file against local PCRedux decision tables.")
    parser.add_argument("--well-calls", required=True, help="Path to well_calls.csv generated by this pipeline.")
    parser.add_argument("--fixture", choices=["stepone_std"], required=True, help="Fixture name for decision-table mapping.")
    parser.add_argument("--pcrredux-tarball", required=True, help="Path to PCRedux_1.2-1.tar.gz.")
    parser.add_argument("--out", required=True, help="Path to JSON comparison report.")
    args = parser.parse_args(argv)

    well_calls_path = Path(args.well_calls)
    tarball = Path(args.pcrredux_tarball)

    if args.fixture == "stepone_std":
        report = compare_stepone(well_calls_path, tarball)
    else:
        raise ValueError(f"Unsupported fixture: {args.fixture}")

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps({"status": "ok", "out": str(out_path), "matched_rows": report["matched_rows"]}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
